In [1]:
!pip install -q --upgrade pip
!pip install -U jaxlib==0.4.4+cuda11.cudnn82 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
!pip install -q --upgrade jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
!pip install -q git+https://www.github.com/google/neural-tangents
!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
!pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cpu.html

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 31.4 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 25.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.2/111.2 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.7/79.7 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 78.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.de

In [1]:
# https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html
%env XLA_PYTHON_CLIENT_PREALLOCATE=false
#%env JAX_PLATFORMS=cpu
%env XLA_PYTHON_CLIENT_ALLOCATOR=platform

env: XLA_PYTHON_CLIENT_PREALLOCATE=false
env: XLA_PYTHON_CLIENT_ALLOCATOR=platform


In [2]:
from google.colab import drive
drive.mount('/content/drive')
%cd /content/drive/MyDrive/Colab Notebooks/Masterarbeit/two_WL_NTK

Mounted at /content/drive
/content/drive/MyDrive/Colab Notebooks/Masterarbeit/two_WL_NTK


In [2]:
%cd /content/drive/MyDrive/Colab Notebooks/Masterarbeit/two_WL_NTK

/content/drive/MyDrive/Colab Notebooks/Masterarbeit/two_WL_NTK


In [3]:
from utils import *
from layers import two_wl_aggregation

In [4]:
import numpy
import neural_tangents as nt
from neural_tangents import stax
from jax import numpy as np
from jax import random
import jax
from torch_geometric.datasets import TUDataset
from torch_geometric.loader import DataLoader
import shutil
import os

In [5]:
# for input "kernel_fn(x1, x2, 'ntk', pattern = (p1,p2))"
# the shape of the kernel after the convolution is:
# x1 = (b1, h1, w1, c1)
# x2 = (b2, h2, w2, c2)
# k = (b1, b2, h1, h2, w1, w2) 


L_branche = stax.serial(
    stax.Conv(100, (1,1)),
    )

Gamma_branche = stax.serial(
    stax.Conv(100, (1,1)),
    two_wl_aggregation(n_nodes=28),
)

two_wl_aggregation_layer = stax.serial(
    stax.FanOut(2), 
    stax.parallel(L_branche, Gamma_branche),
    stax.FanInSum(),
    stax.Relu(),
    )


init_fn, apply_fn, kernel_fn = stax.serial(
    two_wl_aggregation_layer,
    two_wl_aggregation_layer,
    two_wl_aggregation_layer,
    # two_wl_aggregation_layer,
    # two_wl_aggregation_layer,
    #two_wl_aggregation_layer,
    #two_wl_aggregation_layer,
    #two_wl_aggregation_layer,
    #two_wl_aggregation_layer,
    #two_wl_aggregation_layer, # k = (b1, b2, h1, h2, w1, w2)
    stax.GlobalSumPool(), # # k = (b1, b2)
    stax.Dense(1),
)

In [6]:
# load preprocessed data

dataset_name = "MUTAG"
base_path = f"/content/drive/MyDrive/MasterarbeitData/Preprocessed/{dataset_name}"

ys = np.load(base_path + f"/ys.npy")
graphs_edge_features = np.load(base_path + f"/graphs_edge_features.npy")
twl_pattern = np.load(base_path + f"/two_wl_pattern_radius_1.npy")

print(graphs_edge_features.shape) # (188, 28, 1, 7)
print(twl_pattern.shape) # (188, 66, 1, 2)

(188, 28, 28, 8)
(376, 4)


In [11]:
# calculate the kernel range wise 
size = 10
dataset_size = 188
r = 18

base_path = f"/content/drive/MyDrive/MasterarbeitData"
data_path = base_path + f"/Preprocessed/MUTAG"
split_data_path = data_path + f"/splits/size_{size}_range_{r}" 
kernel_path = base_path + f"/Kernels/MUTAG/TWO_WL"

# clear the kernel folder
# shutil.rmtree(kernel_path)

if not os.path.exists(kernel_path):
    os.makedirs(kernel_path)


for i in range(r+1):
  for j in range(r+1):

    l = lambda x : x*size 
    h = lambda x : (1+x)*size if (not x == r) else dataset_size-1
    
    x1_batch_range = list(range(l(i),h(i)))
    x2_batch_range = list(range(l(j),h(j)))
    
    x1 = graphs_edge_features[x1_batch_range,:]
    x2 = graphs_edge_features[x2_batch_range,:]
      
    p1 = twl_pattern[column_in_values(twl_pattern[:,0], np.array(x1_batch_range)),:]
    p2 = twl_pattern[column_in_values(twl_pattern[:,0], np.array(x2_batch_range)),:]

    kernel_matrix = kernel_fn(x1, x2, 'ntk', pattern=(p1, p2))
    np.save(kernel_path + f"/NTK_{h(i)}_{h(j)}", kernel_matrix)

/usr/local/lib/python3.8/dist-packages/neural_tangents/_src/stax/branching.py:399: UserWarning: `FanIn` layers assume independent inputs which is not verified in the code. Please make sure to have at least one `Dense` / `Conv` / `GlobalSelfAttention` etc. layer in each branch.
  warnings.warn('`FanIn` layers assume independent inputs which is not verified'
/usr/local/lib/python3.8/dist-packages/neural_tangents/_src/stax/branching.py:399: UserWarning: `FanIn` layers assume independent inputs which is not verified in the code. Please make sure to have at least one `Dense` / `Conv` / `GlobalSelfAttention` etc. layer in each branch.
  warnings.warn('`FanIn` layers assume independent inputs which is not verified'


In [15]:
kernel_matrix

Array([[143950.25, 143953.05, 143953.05, 143947.6 , 143952.77, 143913.92,
        143951.6 , 143941.56, 143951.81, 143950.25],
       [143953.03, 143961.72, 143961.72, 143948.  , 143964.6 , 143913.06,
        143955.55, 143942.75, 143962.88, 143953.03],
       [143953.03, 143961.72, 143961.72, 143948.  , 143964.6 , 143913.06,
        143955.55, 143942.77, 143962.62, 143952.8 ],
       [143947.38, 143947.78, 143947.78, 143945.69, 143946.12, 143912.94,
        143948.2 , 143939.38, 143945.67, 143947.38],
       [143952.52, 143964.36, 143964.36, 143946.12, 143970.19, 143909.66,
        143955.72, 143941.34, 143966.6 , 143952.52],
       [143913.67, 143912.83, 143912.83, 143912.94, 143909.66, 143893.12,
        143914.06, 143909.44, 143910.84, 143913.67],
       [143951.34, 143955.31, 143955.31, 143948.19, 143955.72, 143914.05,
        143952.92, 143942.31, 143954.53, 143951.34],
       [143941.34, 143942.52, 143942.52, 143939.38, 143941.34, 143909.44,
        143942.31, 143934.1 , 143940.

In [7]:
#this needs ~9GB gpu-ram, takes ~15s on GPU ~2min on CPU (size 4 using XLA_PYTHON_CLIENT_PREALLOCATE=false)
%%time 
size = 10
r = 18
i = 0
j = 0

path = f"/content/drive/MyDrive/MasterarbeitData/Preprocessed/MUTAG/splits/size_{size}_range_{r}"

x1 = np.load(path + f"/graphs_edge_features_1_{i*size}_{(1+i)*size}.npy")
x2 = np.load(path + f"/graphs_edge_features_2_{j*size}_{(1+j)*size}.npy")
p1 = np.load(path + f"/two_wl_pattern_radius_1_1_{i*size}_{(1+i)*size}.npy")
p2 = np.load(path + f"/two_wl_pattern_radius_1_2_{j*size}_{(1+j)*size}.npy")

kernel_matrix = kernel_fn(x1, x2, 'ntk', pattern=(p1, p2))

/usr/local/lib/python3.8/dist-packages/neural_tangents/_src/stax/branching.py:399: UserWarning: `FanIn` layers assume independent inputs which is not verified in the code. Please make sure to have at least one `Dense` / `Conv` / `GlobalSelfAttention` etc. layer in each branch.
  warnings.warn('`FanIn` layers assume independent inputs which is not verified'


CPU times: user 9.43 s, sys: 1.27 s, total: 10.7 s
Wall time: 14.9 s


In [8]:
dataset_size = 188
size = 3
r = 62

base_path = f"/content/drive/MyDrive/MasterarbeitData"
data_path = base_path + f"/Preprocessed/MUTAG"
split_data_path = data_path + f"/splits/size_{size}_range_{r}" 
kernel_path = base_path + f"/Kernels/MUTAG/TWO_WL"
if not os.path.exists(kernel_path):
    os.makedirs(kernel_path)

In [9]:
# clear the kernel folder
# shutil.rmtree(kernel_path)

In [10]:
# at some point this allways fails with 15gb gpu memory
# fails always for some function in utils
# can we make those function more memory efficient?

# with XLA_PYTHON_CLIENT_ALLOCATOR=platform this seems to stay below 5GB 
# GPU-RAM usage for size=4

# calculate kernel from saved preprocessed data
for i in range(r+1):
  for j in range(r+1):

    l = lambda x : x*size 
    h = lambda x : (1+x)*size if (not x == r) else dataset_size-1

    x1 = np.load(split_data_path + f"/graphs_edge_features_1_{l(i)}_{h(i)}.npy")
    x2 = np.load(split_data_path + f"/graphs_edge_features_2_{l(j)}_{h(j)}.npy")
    p1 = np.load(split_data_path + f"/two_wl_pattern_radius_1_1_{l(i)}_{h(i)}.npy")
    p2 = np.load(split_data_path + f"/two_wl_pattern_radius_1_2_{l(j)}_{h(j)}.npy")

    kernel_matrix = kernel_fn(x1, x2, 'ntk', pattern=(p1, p2))
    np.save(kernel_path + f"/NTK_{h(i)}_{h(j)}", kernel_matrix)

/usr/local/lib/python3.8/dist-packages/neural_tangents/_src/stax/branching.py:399: UserWarning: `FanIn` layers assume independent inputs which is not verified in the code. Please make sure to have at least one `Dense` / `Conv` / `GlobalSelfAttention` etc. layer in each branch.
  warnings.warn('`FanIn` layers assume independent inputs which is not verified'


XlaRuntimeError: ignored

Calculate the kernel 1x1 

In [11]:
# load preprocessed data

dataset_name = "MUTAG"
base_path = f"/content/drive/MyDrive/MasterarbeitData/Preprocessed/{dataset_name}"

ys = np.load(base_path + f"/ys.npy")
graphs_edge_features = np.load(base_path + f"/graphs_edge_features.npy")
graph_two_wl_pattern = np.load(base_path + f"/two_wl_pattern_radius_1.npy")

print(graphs_edge_features.shape)
print(graph_two_wl_pattern.shape)

(188, 28, 28, 8)
(376, 4)


In [30]:
i = 3
j = 100
tx1 = np.expand_dims(graphs_edge_features[i,:], 0)
tx2 = np.expand_dims(graphs_edge_features[j,:], 0)
tp1_ind = column_in_values(graph_two_wl_pattern[:,0], np.array([i]))
tp2_ind = column_in_values(graph_two_wl_pattern[:,0], np.array([j]))
tp1 = graph_two_wl_pattern[tp1_ind,:]  
tp2 = graph_two_wl_pattern[tp2_ind,:]  

kernel_fn(tx1, tx2, 'ntk', pattern=(tp1, tp2))

Array([[143938.47]], dtype=float32)

In [28]:
i = 3
j = 3
tx1 = np.expand_dims(graphs_edge_features[i,:], 0)
tx2 = np.expand_dims(graphs_edge_features[j,:], 0)
tp1_ind = column_in_values(graph_two_wl_pattern[:,0], np.array([i]))
tp2_ind = column_in_values(graph_two_wl_pattern[:,0], np.array([j]))
tp1 = graph_two_wl_pattern[tp1_ind,:]  
tp2 = graph_two_wl_pattern[tp2_ind,:]  

kernel_fn(tx1, tx2, 'ntk', pattern=(tp1, tp2))

Array([[143941.8]], dtype=float32)

In [ ]:
kernel_matrix = np.empty((188, 188))

In [20]:
len_x1 = 188
len_x2 = 188

for i in range(len_x1):
  x1 = graphs_edge_features[i,:]
  x1 = np.expand_dims(x1, 0)
  x1_batch_range = list(range(i*size,(1+i)*size))
  p1 = graph_two_wl_pattern[column_in_values(graph_two_wl_pattern[:,0], np.array(x1_batch_range)),:]  
  
  for j in range(len_x2):
    x2 = graphs_edge_features[j,:]
    x2 = np.expand_dims(x2, 0)
    x2_batch_range = list(range(j*size,(1+j)*size))
    p2 = graph_two_wl_pattern[column_in_values(graph_two_wl_pattern[:,0], np.array(x2_batch_range)),:]  

    k = kernel_fn(x1, x2, 'ntk', pattern=(p1, p2))
    kernel_matrix = kernel_matrix.at[i,j].set(np.squeeze(k)) 
    
np.save(kernel_path + f"/NTK_0_188_0_188", kernel_matrix)

/usr/local/lib/python3.8/dist-packages/neural_tangents/_src/stax/branching.py:399: UserWarning: `FanIn` layers assume independent inputs which is not verified in the code. Please make sure to have at least one `Dense` / `Conv` / `GlobalSelfAttention` etc. layer in each branch.
  warnings.warn('`FanIn` layers assume independent inputs which is not verified'


KeyboardInterrupt: ignored

In [19]:
np.squeeze(k)

Array(143950.25, dtype=float32)